args: !!python/object:argparse.Namespace
  accelerator: null
  accumulate_grad_batches: 6
  amp_backend: native
  amp_level: null
  audio_cond: false
  audio_emb_model: STFT
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  batch_size: 8
  benchmark: false
  check_val_every_n_epoch: 1
  checkpoint_callback: null
  data_path: datasets/post_URMP/
  default_root_dir: train_VQGAN
  detect_anomaly: false
  deterministic: false
  devices: null
  disc_channels: 64
  disc_layers: 3
  disc_loss_type: hinge
  discriminator_iter_start: 10000
  downsample:
  - 4
  - 8
  - 8
  embedding_dim: 256
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  fast_dev_run: false
  flush_logs_every_n_steps: null
  gan_feat_weight: 4.0
  gpus: 1
  gradient_clip_algorithm: null
  gradient_clip_val: 1.0
  i3d_feat: false
  image_channels: 3
  image_folder: false
  image_gan_weight: 1.0
  ipus: null
  l1_weight: 4.0
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  log_gpu_memory: null
  logger: true
  lr: 9.0e-05
  max_epochs: null
  max_steps: 100000
  max_time: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  n_codes: 16384
  n_hiddens: 32
  no_random_restart: true
  norm_type: batch
  num_nodes: 1
  num_processes: 1
  num_sanity_val_steps: 2
  num_workers: 16
  overfit_batches: 0.0
  padding_type: replicate
  perceptual_weight: 4.0
  plugins: null
  precision: 32
  prepare_data_per_node: null
  process_position: 0
  profiler: null
  progress_bar_refresh_rate: 100
  reload_dataloaders_every_epoch: false
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: true
  resolution: 9
  restart_thres: 1.0
  resume_from_checkpoint: null
  sample_every_n_frames: 1
  sequence_length: 16
  smap_cond: 0
  smap_only: false
  spatial_length: 15
  stft_data: false
  stochastic_weight_avg: false
  strategy: null
  sync_batchnorm: false
  terminate_on_nan: null
  text_cond: false
  text_emb_model: null
  text_seq_len: 64
  text_stft_cond: false
  tpu_cores: null
  track_grad_norm: -1
  truncate_captions: false
  val_check_interval: 1.0
  video_gan_weight: 1.0
  vtokens: false
  vtokens_pos: false
  weights_save_path: null
  weights_summary: top
